# src/web_gui_pkg/src/web_gui_pkg/page_startup.py

from nicegui import ui
import os
import stat
from .core_logic import NiceGUIRos_instance
from .config import ROBOT_NAME, HOME_DIR, ROS_SETUP_COMMAND


@ui.page("/startup")
def startup_page():
    # 스크립트 저장 경로
    SCRIPT_PATH = "/home/hightorque/start_up.sh"

    # 선택된 항목을 저장할 딕셔너리 {(pkg_name, file_name): checkbox_element}
    checkboxes = {}

    # ----- 헤더 -----
    with ui.header().classes("bg-slate-900 shadow-lg"):
        with ui.row().classes("w-full items-center h-full max-w-screen-xl mx-auto px-4"):
            ui.html("""<img src="/static/wego_logo.png" style="height: 32px;">""")
            ui.label(ROBOT_NAME + " Startup Generator").classes("text-white font-bold text-lg")
            ui.space()
            ui.button("부팅 설정", icon="save_as", color="green-6").props("flat").on("click", lambda: ui.navigate.to("/startup", new_tab=False))
            ui.button("메인으로", icon="home", color="indigo-6").props("flat").on("click", lambda: ui.navigate.to("/", new_tab=False))

    # ----- 스크립트 생성 로직 -----
    def generate_script():
        selected_items = []
        for (pkg, file_name), cb in checkboxes.items():
            if cb.value:
                selected_items.append((pkg, file_name))

        if not selected_items:
            ui.notify("선택된 Launch 파일이 없습니다.", type="warning")
            return

        try:
            with open(SCRIPT_PATH, "w") as f:
                f.write("#!/bin/bash\n\n")
                f.write("# Auto-generated by Web GUI\n")

                # config.py에 있는 ROS setup 명령어들을 줄바꿈해서 넣기
                # (세미콜론으로 구분된 명령어를 보기 좋게 분리)
                setup_cmds = ROS_SETUP_COMMAND.split(";")
                for cmd in setup_cmds:
                    if cmd.strip():
                        f.write(f"{cmd.strip()}\n")

                f.write("\n# Wait for ROS Core (Optional but recommended)\n")
                f.write("sleep 1\n\n")

                f.write("# Launch selected packages\n")
                for pkg, file_name in selected_items:
                    # cam_setting.launch 같은 가상 파일 제외
                    if pkg == "web_gui_pkg" and file_name == "cam_setting.launch":
                        continue

                    cmd = f"roslaunch {pkg} {file_name}"
                    # usb_cam의 경우 인자 추가 예시 (필요시 로직 구체화)
                    if pkg == "usb_cam" and file_name == "usb_cam-test.launch":
                        # 기본값으로 저장
                        cmd += " video_device:=/dev/video0"

                    f.write(f"echo 'Starting {file_name}...'\n")
                    f.write(f"{cmd} &\n")  # 백그라운드 실행
                    f.write("sleep 2\n\n")  # 실행 간격 텀

                f.write("wait\n")

            # 실행 권한 부여 (+x)
            st = os.stat(SCRIPT_PATH)
            os.chmod(SCRIPT_PATH, st.st_mode | stat.S_IEXEC)

            ui.notify(f"생성 완료: {SCRIPT_PATH}", type="positive")

        except Exception as e:
            ui.notify(f"생성 실패: {e}", type="negative")

    # ----- 메인 UI -----
    with ui.column().classes("p-4 w-full max-w-screen-xl mx-auto"):
        ui.label("부팅 시 실행할 Launch 파일을 선택하세요").classes("text-xl font-bold mb-4")

        # 스캔 데이터가 없으면 경고
        if not NiceGUIRos_instance.launch_files_data:
            ui.label("패키지 정보를 불러오는 중이거나 없습니다. 메인 페이지에서 스캔을 완료해주세요.").classes("text-red-500")
            ui.button("새로고침", icon="refresh", on_click=lambda: ui.navigate.reload())
        else:
            with ui.row().classes("w-full mb-4 justify-end"):
                ui.button("스크립트 생성 (start_up.sh)", icon="save", color="green-6", on_click=generate_script)

            # 패키지별 리스트 렌더링
            with ui.column().classes("w-full gap-4"):
                for pkg, pkg_data in sorted(NiceGUIRos_instance.launch_files_data.items()):
                    # 가상 패키지나 파일 제외하고 싶으면 여기서 필터링

                    with ui.card().classes("w-full"):
                        ui.label(f"📦 {pkg}").classes("text-lg font-bold bg-slate-100 w-full p-2 rounded")

                        with ui.grid(columns=1).classes("w-full gap-2 p-2 sm:grid-cols-2 lg:grid-cols-3"):
                            for file_name in sorted(pkg_data["files"].keys()):
                                # cam_setting.launch는 제외
                                if file_name == "cam_setting.launch":
                                    continue

                                with ui.row().classes("items-center"):
                                    cb = ui.checkbox(file_name)
                                    checkboxes[(pkg, file_name)] = cb

    # ----- 푸터 -----
    with ui.footer().classes("justify-center items-center h-6 bg-gray-200"):
        ui.label("Start Up Generator v1.0").classes("text-xs text-gray-500")
