# src/web_gui_pkg/src/web_gui_pkg/page_startup.py

from nicegui import ui
import os
import stat
import glob
import shutil
from .core_logic import NiceGUIRos_instance
from .config import ROBOT_NAME, HOME_DIR, ROS_SETUP_COMMAND

@ui.page("/startup")
def startup_page():
    
    # [설정] 디렉토리 구조
    STARTUP_ROOT = os.path.join(HOME_DIR, "startup")
    DEFAULT_DIR = os.path.join(STARTUP_ROOT, "default")
    ADDITIONAL_DIR = os.path.join(STARTUP_ROOT, "additional")
    
    os.makedirs(DEFAULT_DIR, exist_ok=True)
    os.makedirs(ADDITIONAL_DIR, exist_ok=True)

    AUTOSTART_DIR = os.path.join(HOME_DIR, ".config", "autostart")
    MY_DESKTOP_FILE = os.path.join(AUTOSTART_DIR, "wego_gui_user_startup.desktop")
    WRAPPER_SCRIPT = os.path.join(STARTUP_ROOT, "launcher_wrapper.sh")

    checkboxes = {}
    
    # UI 참조 변수 (반응형 제어를 위해)
    user_list_card = None 

    # ----- 헤더 -----
    with ui.header().classes("bg-slate-900 shadow-lg"):
        with ui.row().classes("w-full items-center h-full max-w-screen-xl mx-auto px-4"):
            ui.html("""<img src="/static/wego_logo.png" style="height: 32px;">""")
            ui.label(ROBOT_NAME + " Startup Manager").classes("text-white font-bold text-lg")
            ui.space()
            ui.button("메인으로", icon="home", color="indigo-6").props("flat").on(
                "click", lambda: ui.navigate.to("/", new_tab=False)
            )

    # ========================================================
    # [Logic] 기능 구현
    # ========================================================
    def open_save_dialog():
        with ui.dialog() as dialog, ui.card():
            ui.label("새 스크립트 생성").classes("text-lg font-bold")
            name_input = ui.input("파일 이름 (예: kid_mode)", placeholder="start_up").classes("w-full")
            
            def _save():
                name = name_input.value.strip()
                if not name:
                    ui.notify("이름을 입력해주세요.", type="warning"); return
                if not name.endswith(".sh"): name += ".sh"
                
                save_path = os.path.join(ADDITIONAL_DIR, name)
                create_script_file(save_path)
                dialog.close()
                ui.navigate.reload()

            with ui.row().classes("w-full justify-end"):
                ui.button("취소", on_click=dialog.close).props("flat")
                ui.button("저장", on_click=_save)
        dialog.open()

    def create_script_file(path):
        selected_items = []
        for (pkg, file_name), cb in checkboxes.items():
            if cb.value: selected_items.append((pkg, file_name))

        if not selected_items:
            ui.notify("선택된 Launch 파일이 없습니다.", type="warning"); return

        try:
            with open(path, "w") as f:
                f.write("#!/bin/bash\n\n")
                f.write("# Auto-generated by Web GUI\n")
                setup_cmds = ROS_SETUP_COMMAND.split(";")
                for cmd in setup_cmds:
                    if cmd.strip(): f.write(f"{cmd.strip()}\n")
                
                f.write("\n# Launch selected packages\n")
                for pkg, file_name in selected_items:
                    if pkg == "web_gui_pkg" and file_name == "cam_setting.launch": continue
                    
                    cmd = f"roslaunch {pkg} {file_name}"
                    if pkg == "usb_cam" and file_name == "usb_cam-test.launch":
                        cmd += " video_device:=/dev/video0"
                    
                    f.write(f"echo 'Starting {file_name}...'\n")
                    f.write(f"{cmd} &\n") 
                    f.write("sleep 2\n\n")
                f.write("wait\n")

            st = os.stat(path)
            os.chmod(path, st.st_mode | stat.S_IEXEC)
            ui.notify(f"생성 완료: {os.path.basename(path)}", type="positive")
        except Exception as e:
            ui.notify(f"생성 실패: {e}", type="negative")

    def update_list_ui_state(is_on):
        """스위치 상태에 따라 목록 UI를 활성/비활성 처리"""
        if user_list_card:
            if is_on:
                # 활성화: 투명도 제거, 클릭 가능
                user_list_card.classes(remove="opacity-40 pointer-events-none grayscale")
            else:
                # 비활성화: 흐리게, 흑백, 클릭 불가
                user_list_card.classes(add="opacity-40 pointer-events-none grayscale")

    def toggle_global_autostart(e):
        is_on = e.value
        # UI 상태 즉시 업데이트
        update_list_ui_state(is_on)

        if is_on: # ON
            try:
                os.makedirs(AUTOSTART_DIR, exist_ok=True)
                with open(WRAPPER_SCRIPT, "w") as f:
                    f.write("#!/bin/bash\n")
                    f.write(f"{ROS_SETUP_COMMAND}\n\n")
                    f.write("echo '======================================'\n")
                    f.write("echo '   Wego GUI User Startup Launcher     '\n")
                    f.write("echo '======================================'\n\n")
                    f.write("echo 'Waiting 50 seconds for Robot Initialization...'\n")
                    f.write("for i in {50..1}; do echo -ne \"Running in $i seconds... \\r\"; sleep 1; done\n")
                    f.write("echo -e \"\\n[Launcher] Timer finished. Checking ROS...\"\n\n")
                    f.write("until rostopic list > /dev/null 2>&1; do echo 'Waiting for ROS Master...'; sleep 2; done\n")
                    f.write("echo '[Launcher] ROS Ready! Executing enabled user scripts...'\n\n")
                    f.write(f"for f in {ADDITIONAL_DIR}/*.sh; do\n")
                    f.write("  if [ -f \"$f\" ]; then echo \"[Launcher] Running $f ...\"; bash \"$f\" & fi\n")
                    f.write("done\n\n")
                    f.write("echo '[Launcher] All scripts triggered.'\n")
                    f.write("wait\n")
                    f.write("sleep 1000\n") 

                st = os.stat(WRAPPER_SCRIPT)
                os.chmod(WRAPPER_SCRIPT, st.st_mode | stat.S_IEXEC)

                term_cmd = ""
                if shutil.which("gnome-terminal"):
                    term_cmd = f"gnome-terminal --window --title='User Scripts Launcher' -- bash -c '{WRAPPER_SCRIPT}; exec bash'"
                elif shutil.which("xfce4-terminal"):
                    term_cmd = f"xfce4-terminal --title='User Scripts Launcher' --hold --command='bash -c {WRAPPER_SCRIPT}'"
                else:
                    term_cmd = f"x-terminal-emulator -e 'bash -c \"{WRAPPER_SCRIPT}; read\"'"

                with open(MY_DESKTOP_FILE, "w") as f:
                    f.write("[Desktop Entry]\n")
                    f.write("Type=Application\n")
                    f.write("Name=Wego GUI User Startup\n")
                    f.write(f"Exec={term_cmd}\n")
                    f.write("Hidden=false\n")
                    f.write("NoDisplay=false\n")
                    f.write("X-GNOME-Autostart-enabled=true\n")
                
                ui.notify(f"자동 실행 등록됨! (부팅 50초 후 실행)", type="positive")
            except Exception as err:
                ui.notify(f"설정 실패: {err}", type="negative"); e.source.set_value(False)
        else: # OFF
            if os.path.exists(MY_DESKTOP_FILE): os.remove(MY_DESKTOP_FILE)
            if os.path.exists(WRAPPER_SCRIPT): os.remove(WRAPPER_SCRIPT)
            ui.notify("사용자 스크립트 자동 실행: 꺼짐", type="warning")

    def toggle_file_status(e, name):
        base_path = os.path.join(ADDITIONAL_DIR, name)
        target_path = base_path + ".sh"
        disabled_path = base_path + ".sh.disabled"

        if e.value: # ON
            if os.path.exists(disabled_path):
                os.rename(disabled_path, target_path)
                ui.notify(f"{name} 활성화됨", type="positive")
            elif os.path.exists(target_path): pass
            else: ui.notify("파일 오류", type="negative"); e.source.set_value(False)
        else: # OFF
            if os.path.exists(target_path):
                os.rename(target_path, disabled_path)
                ui.notify(f"{name} 비활성화됨", type="warning")
            elif os.path.exists(disabled_path): pass
            else: ui.notify("파일 오류", type="negative"); e.source.set_value(True)

    def delete_file(name):
        p1 = os.path.join(ADDITIONAL_DIR, name + ".sh")
        p2 = os.path.join(ADDITIONAL_DIR, name + ".sh.disabled")
        try:
            if os.path.exists(p1): os.remove(p1)
            if os.path.exists(p2): os.remove(p2)
            ui.notify(f"{name} 삭제됨", type="info")
            ui.navigate.reload()
        except Exception as e:
            ui.notify(f"삭제 실패: {e}", type="negative")

    def get_additional_files():
        files = glob.glob(os.path.join(ADDITIONAL_DIR, "*"))
        result = []
        for f in files:
            fname = os.path.basename(f)
            if fname.endswith(".sh"):
                result.append({"name": fname[:-3], "enabled": True})
            elif fname.endswith(".sh.disabled"):
                result.append({"name": fname[:-12], "enabled": False})
        return sorted(result, key=lambda x: x["name"])

    # --------------------------------------------------------
    # [UI] 레이아웃
    # --------------------------------------------------------
    with ui.column().classes("p-4 w-full max-w-screen-xl mx-auto space-y-6"):
        
        # 1. 시스템 관리
        with ui.card().classes("w-full border-l-4 border-slate-500"):
            ui.label("⚙️ 부팅 프로세스 관리 (System & Startup)").classes("text-xl font-bold")
            
            with ui.row().classes("w-full items-center justify-between px-4 py-3 bg-gray-100 rounded"):
                with ui.column().classes("gap-0"):
                    ui.label("1. Default System (Factory)").classes("font-bold text-gray-700")
                    ui.label(f"경로: {DEFAULT_DIR}").classes("text-xs text-gray-400")
                ui.chip("Always ON", color="gray", icon="lock").props("dense")

            with ui.row().classes("w-full items-center justify-between px-4 py-3 bg-indigo-50 rounded mt-2"):
                is_global_on = os.path.exists(MY_DESKTOP_FILE)
                with ui.column().classes("gap-0"):
                    ui.label("2. User Scripts (Additional)").classes("font-bold text-indigo-700")
                    ui.label("활성화 시, 부팅 직후 터미널이 열리고 50초 카운트다운 후 실행됩니다.").classes("text-xs text-indigo-500")
                ui.switch("부팅 시 실행", value=is_global_on, on_change=toggle_global_autostart).props("color=indigo size=lg")

        # 2. 사용자 스크립트 (UI 변수에 할당하여 상태 제어)
        user_list_card = ui.card().classes("w-full border-l-4 border-green-500 transition-all duration-300")
        with user_list_card:
            with ui.row().classes("w-full items-center justify-between"):
                with ui.column().classes("gap-0"):
                    ui.label("📂 사용자 스크립트 목록").classes("text-xl font-bold")
                    ui.label(f"경로: {ADDITIONAL_DIR}").classes("text-xs text-gray-500")
                ui.button(icon="refresh", on_click=lambda: ui.navigate.reload()).props("flat round")

            # [안내 문구 추가]
            ui.label("💡 알림: 목록을 변경(ON/OFF)한 후에는 순서 적용을 위해 상단의 [부팅 시 실행] 스위치를 껐다가 다시 켜주세요.").classes(
                "w-full text-sm text-orange-800 bg-orange-100 p-2 rounded mb-2 font-medium"
            )

            user_files = get_additional_files()
            if not user_files:
                ui.label("저장된 스크립트가 없습니다. 아래에서 생성해주세요.").classes("text-gray-400 italic ml-4 py-4")
            else:
                with ui.grid(columns=1).classes("w-full gap-2 mt-2 lg:grid-cols-2"):
                    for item in user_files:
                        with ui.row().classes("items-center justify-between px-4 py-2 bg-green-50 rounded border border-green-100"):
                            ui.label(item["name"] + ".sh").classes("font-medium")
                            with ui.row().classes("items-center"):
                                ui.switch(value=item["enabled"], on_change=lambda e, n=item["name"]: toggle_file_status(e, n)).props("color=green")
                                ui.button(icon="delete", color="red", on_click=lambda _, n=item["name"]: delete_file(n)).props("flat dense round")

        # 초기 UI 상태 적용 (스위치 꺼져있으면 흐리게)
        if not is_global_on:
            user_list_card.classes(add="opacity-40 pointer-events-none grayscale")

        # 3. 생성기
        with ui.card().classes("w-full"):
            with ui.row().classes("w-full items-center justify-between mb-4"):
                ui.label("📝 새 스크립트 만들기").classes("text-xl font-bold")
                ui.button("저장 (.sh 생성)", icon="save", color="green-6", on_click=open_save_dialog)

            if not NiceGUIRos_instance.launch_files_data:
                ui.spinner('dots', size='lg')
                ui.label("패키지 스캔 중...")
            else:
                with ui.column().classes("w-full gap-4"):
                    for pkg, pkg_data in sorted(NiceGUIRos_instance.launch_files_data.items()):
                        if pkg == "web_gui_pkg": continue 
                        with ui.expansion(f"📦 {pkg}", icon="folder", value=True).classes("w-full bg-slate-50"):
                            with ui.grid(columns=1).classes("w-full gap-2 p-2 sm:grid-cols-2 lg:grid-cols-3"):
                                for file_name in sorted(pkg_data["files"].keys()):
                                    if file_name == "cam_setting.launch": continue
                                    with ui.row().classes("items-center"):
                                        cb = ui.checkbox(file_name)
                                        checkboxes[(pkg, file_name)] = cb

    with ui.footer().classes("justify-center items-center h-6 bg-gray-200"):
        ui.label("Startup Manager v5.7 (UX Improved)").classes("text-xs text-gray-500")