#!/bin/bash

# Auto-generated by Web GUI
source /opt/ros/noetic/setup.bash
source /home/hightorque/realsense_ws/devel/setup.bash
source /home/hightorque/wego_minipi_ws/devel/setup.bash

# Launch selected packages
echo 'Starting joy_teleop.launch...'
roslaunch sim2real_master joy_teleop.launch &
sleep 2

echo 'Starting twist_mux.launch...'
roslaunch wego_twist_mux twist_mux.launch &
sleep 2

wait
