#!/bin/bash

# Auto-generated by Web GUI
# 이 스크립트는 master_autostart.sh가 완료되기를 기다렸다가 실행됩니다.

source /opt/ros/noetic/setup.bash
source /home/hightorque/realsense_ws/devel/setup.bash
source /home/hightorque/soccer_ws/devel/setup.bash

# === [WAIT SEQUENCE START] ===
echo '[GUI Startup] Waiting for ROS Core...'
until rostopic list > /dev/null 2>&1; do sleep 2; done
echo '[GUI Startup] ROS Core detected!'

echo '[GUI Startup] Waiting for master_autostart.sh to finish...'
while pgrep -f 'master_autostart.sh' > /dev/null; do
    sleep 1
done
echo '[GUI Startup] Master script finished. Starting user nodes...'
sleep 5
# === [WAIT SEQUENCE END] ===

# Launch selected packages

echo 'Starting twist_mux.launch...'
roslaunch wego_twist_mux twist_mux.launch &
sleep 2

echo 'Starting joy_teleop_kid.launch...'
roslaunch sim2real_master joy_teleop_kid.launch &
sleep 2
wait
